### PR TITLE
All patients

### LINKED ISSUE #165: All patients view is slow to load
@zhouminerva @justinrporter 
Sooo, the scope for this is kinda large and will involve rewriting a lot of database queries
My suspicion is that because many columns of the all_patients table are not columns directly on the Patient table, what actually happens is

1. The [all_patients](https://github.com/SaturdayNeighborhoodHealthClinic/osler/blob/master/pttrack/views.py#L349) view asks for `patient_list = mymodels.Patient.objects.all().order_by('last_name')`. From a database query perspective, this should be 1 database hit to ask for `mymodels.Patient.objects.all()`, which gets all properties (columns) directly on the Patient database table
2. We get to the loop in the [template](https://github.com/SaturdayNeighborhoodHealthClinic/osler/blob/master/pttrack/templates/pttrack/all_patients.html#L18), which wants patient age, gender, list of case managers, clinic date and signer of the latest workup, history date of the last history, and status. Unfortunately, the database isn't prescient and doesn't know we want all these things not in the patient table, that are joined by foreign keys, etc.
3. Most of these properties are not on the Patient table. Thus for every patient, and for every property not directly on the Patient table, the templating makes a hit to the the database to get this joined property. [This django ref](https://docs.djangoproject.com/en/2.0/ref/models/querysets/#select-related) describes this problem (and the general idea of the solution, which is to explicitly tell django to join/follow the relationship).
4. This is made worse by how some of these properties are computed. For instance, computing [status](https://github.com/SaturdayNeighborhoodHealthClinic/osler/blob/master/pttrack/models.py#L267) asks for `active_action_items`, `inactive_action_items`, and `done_action_items`. [Each of these](https://github.com/SaturdayNeighborhoodHealthClinic/osler/blob/master/pttrack/models.py#L238) makes a separate database query, filtering on the ActionItem table. Meaning that asking for a patient status makes 3 hits to the database.
5. Instead of making 1 database call, we end up making 1 + (num patients * >10). Assuming 500 patients that's > thousands of database hits
6. The all_patients view is slow because hits to the database are I/O, and I/O is costly time-wise

So, a major speedup will come from not hitting the database for every patient (as long as we take out the 500, it's totally okay to hit the db 10 times). Meaning everything the tables needs, we need to explicitly pull upfront. There are two approaches I'm thinking about, and with the complexity of a lot of these queries I'm thinking of going for a hybrid:

1. Slowly fold each property into a loooong all patients + associated information query. This means we only hit the database once, but given the complexity of all these properties this will be difficult to do in entirety.
2. On the other extreme, we could load all tables into memory as [pandas dataframes](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.html), and do all the joins in memory, which would be easier than figuring out a complex query for something like patient status. But this means we have to joins manually, not taking advantage of the database relationships we wrote (plus costing a ton of memory space).
3. A mix of the above. For simple relationships, we can write a query to tell django to join. For more complicated things we can load whole tables into memory, then do the filter/joins there. This is the easy solution, but has the potential for excessive memory consumption.

Some questions I have:

1. Where is `workup_set`? I see `self.workup_set` on the Patient model twice, but searching the code base I can't seem to find where the property is derived from.
2. What is the memory on the machine osler is deployed on (tiny MB, or GB?)
3. How many rows are there in the Patients and ActionItems tables?
Answers for 2 and 3 limit the degree to which we can just load entire tables into memory.

About timeline:
I'm gonna say this entire thing is a 3-4 week effort, because

- there are 8 properties
- only one (gender) is directly on the Patient table
- a lot of them are kinda complicated properties defined by functions
- every one needs to be rewritten to not hit the database again
- I am not familiar with django query language (how to use select_related, etc.)

I forgot that I won't be back home till next week, so I'm gonna put the estimate for rewriting every single property at 4-5 weeks from now.

That said, we should see small latency improvements for every property that does not require a db query. So there is an option of gradually rolling out small improvements, even if the big one will come from not looping over all patients.

Fixing this may remove the need for #131

### PR DESCRIPTION
**Pull request by JoLBree**
Fixes #165

Modified the all patients query and how the template accessed query results to reduce the number of database trips in rendering the all patients table.

The history field is still being accessed for every patient, because it's a 3rd party library (simple_history) that I couldn't figure out how to prefetch for all patients. That said, there should be a notable speed up with this fix; if it's still slow I can look more into folding in the history field.

@justinrporter @zhouminerva

### CODE REVIEW

**Comment by JoLBree** [comment]
Questions

1. I don't know, I'd say the best way to simulate that is to a generate a whole bunch of patients and action items... but when it comes to these database things we'll only really know on the real data which for privacy stuff we obviously can't take out, so I'd say we'll find out when we deploy.
2. I don't know how concerned we are with that, what do you think? It's currently gated [here](https://github.com/SaturdayNeighborhoodHealthClinic/osler/blob/all_patients/osler/urls.py#L21), so it's installed by not routed to urls. Are there separate requirement.txt files for dev and production? If so then yes we should add it to dev and take if off the production one. If we don't, we can split into two requirement files if we are concerned with this.
3. Why get rid of the in-memory loop? We can change it to three querysets of all patients to get all active, all inactive, and all done, but I like that less because the subsequent logic for the string message would have to be written either in the view (by manipulating it as a pandas dataframe, which I don't want to introduce if we don't have to) or in the template (which is ugly and not the place for complicated logic). I like it in memory because it means that we can have a status() function and that it lives in the model, which makes it more easy to reason about here is how we calculate status for one patient, instead of here is how we batch calculate status for all patients using additional syntax (pandas) that not everyone contributing to this repo may be familiar with. In any case we have to hold all three types of action items, so I feel like the memory footprint is actually the same.
4. Probably not meant to be there, good catch! I'll take a look at that, and write a test for whatever is breaking because of that pass (might be a while because I need to fix my test setup first, I haven't actually done that and have just been pushing to run tests)

Will work on the requests!

I'm not sure if there's a way I can mark this PR as not yet done?

**Comment by JoLBree** [comment]
@justinrporter What should I do about the code coverage? It's complaining that the if debug (i.e. if dev), add the debug toolbar is not tested and thus reducing coverage. The toolbar is just a dev thing and I think it's reasonable to not test it's addition.

**Comment by justinrporter** [comment]
> What should I do about the code coverage 

I'm trying to add a config file so that coverage doesn't try to run coverage for the tests.

**Comment by justinrporter** [comment]
Oh, no I see what's going on. Yes, this is fine. If it is ready I will just merge it manually!

**Comment by JoLBree** [comment]
Yup, it's ready. Thanks! After it's deployed keep me updated if the speed up works.

**Comment by justinrporter** [comment]
@JoLBree I just deployed this at the all-patients view loads _substantially_ faster. 10 seconds rather than like a minute or two!

**Comment by JoLBree** [comment]
@justinrporter Woohoo! Wow I didn't realize it used to take a minute or two...
I'm in a horribly busy spell till about the end of December, but if this is still an issue come January I'd be interested in taking another look, 10 seconds is still pretty long... Or work on whatever else needs working on at that time.
Glad to know this works!

**Pull request merged**
