### PR TITLE
Issue clean

### PR DESCRIPTION
**Pull request by nakul2234**

### CODE REVIEW

**Comment by justinrporter** [comment]
Nice. Good work! I especially like how tight `home_page` is now.

The `is_staff` parameter for `ProviderType` is a good idea, but we already represent this idea through the `User.is_staff` parameter. I think this might be a situation where we're going to have to re-represent this information. Could you modify `ProviderCreate` to write through to the `User` object a `True` for `User.is_staff` if the new user is a coordinator?

**Comment by nakul2234** [comment]
I guess I should name the variable something else, but I was imaging a future where other people may have access that are not superusers/have additional admin access. That way, we can specify based on if they are coordinator, volunteer, social work student, etc. what their views will look like on the home page based on the is_staff as a part of the provider type.

**Comment by justinrporter** [comment]
> That way, we can specify based on if they are coordinator, volunteer, social work student, etc. what their views will look like on the home page based on the is_staff as a part of the provider type.

This is a good idea! Perhaps we should come up with a different name to prevent confusion with the `User` property, which implies something more about access to the back end...

**Comment by nakul2234** [comment]
@justinrporter Maybe we should just change the User property form is_staff to is_admin? I cannot think of anything else besides having access to the admin panel that coordinators have that we would not want other "staff" of SNHC to have access to.

**Comment by justinrporter** [comment]
If we think `User.is_staff` is the same as the proposed `ProviderType` property, we probably shouldn't represent it separately. Instead, we should just always use the `User.is_staff` flag, right?

**Comment by nakul2234** [comment]
The link to the admin panel depends on `<is_staff>`, but we do not want all staff to have Admin access necessary. I was thinking `<is_staff>` makes more sense as a part of provider type, and then we just check if the user has superuser permissions to determine if they can have access to the admin panel. But, if you think it makes more sense to be a part of the User, I can edit it back.

**Comment by justinrporter** [comment]
> we do not want all staff to have Admin access necessary

What else were you thinking that `is_staff` would represent? The way we're using it now, only Coordinators have `User.is_staff` true. Also, I think `User.is_staff` determines if the user can view the admin panel, and the admin panel permissions determine what the user can actually do from the admin panel. I'm not totally sure about that, though.

However, I wonder if we don't want to keep the `is_staff` ProviderType property, which indicates if users with that `ProviderType` should be marked with a true `User.is_staff` when created. Does that make sense? Another solution might be to monkeypatch `User` to ask `Provider.clinical_roles` if any of them have `ProviderType.is_staff` true.

What do you think?

**Comment by nakul2234** [comment]
I guess the only reason I used the `is_staff`was I needed a way to not have the code use "Coordinator" and other text comparisons to indicate what kind of provider type a person is in templates when generating different views depending on the provider. 

I was thinking about the future when we would add a user that we wanted to have a particular view (the same one as the coordinators), but we do not want them to see the admin panel link. 

We just have to decide how we want to customize views on provider type without using text-based validators. Either via variables in providertype or some other method. I could just make a `view` variable in ProviderType where I assign a value to each custom home-screen view I want available to providertype?

**Comment by nakul2234** [comment]
@justinrporter I think this is ready to ship. I will move on to the other projects (tabbed views and timeline) tomorrow

**Comment by justinrporter** [comment]
So, I like calling it `ProviderType.staff_view`, but it seems like there are a bunch of places where you do

```python
request.session['is_staff'] = active_provider_type.staff_view
```

or

```html
{% if request.session.is_staff %}
```

Shouldn't we call them the same thing?

**Comment by nakul2234** [comment]
fixed!

**Comment by justinrporter** [comment]
Cool. A few more things I'm noticing:

1) It looks like in `patient_detail.html` you have cut and pasted each of the three action item collapsable divs... IIRC doing this on the other side of the page (for the `Notes`) is what led to a bug that made it into production last time, making it impossible to expand two of the three collapsables. Please refactor this code to use a loop.

2) It looks like you've created two migrations in pttrack, 0002 and 0003, where 0003 immediately renames something in 0002. Could you squash these migrations?

3) There are a couple of places where your whitespace usage is not preferred. For example, on `pttrack/views.py:280` we have:

```python
zipped_list = zip(["Active Patients", "Active Action Items", "Pending Action Items"], 
                    [pt_list_active, pt_list_ai_active, pt_list_ai_inactive])
```

where we should have

```python
zipped_list = zip(["Active Patients", "Active Action Items", "Pending Action Items"], 
                  [pt_list_active, pt_list_ai_active, pt_list_ai_inactive])
```

**Comment by nakul2234** [comment]
1. I do not think it would be that beneficial for the different kinds of notes to have to make it all one loop. With so many lists being zipped, being accessed in the loops of the template, and all the `if statements` it would have to have, it would hurt readability more than help. 

Last time the bug was due to me not knowing that each panel needed to have a separate `id` to expand properly and not a problem with copy and paste.

I can make a loop for the action items since they are similar enough.

2. Done
3. Fixed

**Comment by justinrporter** [comment]
> 1. I do not think it would be that beneficial for the different kinds of notes to have to make it all one loop. With so many lists being zipped, being accessed in the loops of the template, and all the `if statements` it would have to have, it would hurt readability more than help. 

So, I'm concerned about the amount of repetitive html in that template. Do you have any ideas at all for reducing it?

**Comment by nakul2234** [comment]
>So, I'm concerned about the amount of repetitive html in that template. Do you have any ideas at all for reducing it?

Each panel code for the `notes` is unique enough that it justifies the repetition in my opinion. I collapsed it down a bit, but there just needs to be that many tags for the panels to work. I think more advanced bootstrap features will require this.

Also, the tests pass on my computer but not on Travis CI. Weird.

**Comment by justinrporter** [comment]
> I collapsed it down a bit

It really looks a lot better to me now! The HTML is complicated, but it's the repetition that I don't like.

Looks good. Ship it. Also, don't forget to update halstead with the new code! Let's use it on Saturday.

**Pull request merged**
