### PR TITLE
Added name validator and run test instructions

### PR DESCRIPTION
**Pull request by JoLBree**
Also changed some readme typos

### CODE REVIEW

**Comment by JoLBree** [comment]
Addresses issue #99

**Comment by justinrporter** [comment]
Is this ready to go?

**Comment by JoLBree** [comment]
It used to be...... now it doesn't work. Trying to figure out what's wrong now.

**Comment by justinrporter** [comment]
Great. Update this branch to master (this will trigger the CI again) and we can pull it into master!

**Pull request merged**
