### PR TITLE
adjustments to drop down menu options

### PR DESCRIPTION
**Pull request by radhikajain**
changed ethnicities
adjusted diagnosis categories

### CODE REVIEW

**Comment by justinrporter** [comment]
Tests pass, init_db.py still works. Nice job!

**Comment by justinrporter** [comment]
@radhikajain which of the ethnicity categories would I fall in to? I see african-american, but nothing for americans of european origin?

**Comment by justinrporter** [comment]
Wait, so I found caucasian, but how did we choose Bolivian, Bosnian, and Brazilian, but not Belgian or Bengladeshi?

**Comment by ecd25** [comment]
Didn't we discuss changing this to just be a fill in on your own option or choosing the top 10-15 from Snhc or stl historically?

**Comment by radhikajain** [comment]
Justin, those categories are completely arbitrary; I just copied whatever was in the old patient tracking because I didn’t have a better way to be completely exhaustive. As you’ve identified, a number of countries are currently missing. 


Davis, we could take the top ten from the SNHC but that will not reflect missing ethnicities, as Justin pointed out. Top ten from St. Louis might make more sense. I think we should just leave what we have and add in more as they come up (including those
 from STL top ten that aren’t currently on the list).


It will be blank on the paper intake form. It’s hard to code options + fill-in other, according to Justin, so we will have to decide whether we want it completely fill-in blank text or as many exhaustive drop down options as possible.

**Comment by justinrporter** [comment]
I don't want to say it's hard to do options + fill-other, I just don't know how to do it and googling does not yield a super-obvious/straightforward answer. I am sure it is possible, it's just not a launch feature, I don't think.

@radhikajain I didn't realize. I saw that you'd updated it a couple of times and thought maybe that's what you wanted for a final. I kind of like the top 10 + other, because I don't know if it makes sense to even try to track smaller demographic groups. But I think the ultimate solution will be for me to implement a "MC + other-please-specify option". For some reason this is not built in to the framework I'm using.

And a quick point of clarification: options are not hard-coded, because you can always go to the admin panel and add more. It takes really like < 30 seconds once you know how to do it.

**Comment by ecd25** [comment]
I like just fill in the blank.

**Pull request merged**
