### PR TITLE
Ui improvements

### PR DESCRIPTION
**Pull request by nakul2234**
Concerning #51 mostly, this cleans up the UI and adds a lot of nice features to improve navigation and rendering of data.

### CODE REVIEW

**Comment by justinrporter** [comment]
1) When do patients automatically inactivate? Optimally, they would inactivate sometime the next day/week, right?
2) It doesn't look like any new tests were added in this branch. Is that right? It seems like a fair amount of functionality was added...

**Comment by nakul2234** [comment]
Changelog
- Buttons aligned and made bigger on Patient Details
- Notes grouped into expandable panels on Patient Details
- Demographic Information Aligned on Patient Details
- The new Patient Detail template is expandable so you can send it as many section headers and object lists you want
- I made the inactive/active controls to be present on the home screen in the lists (Only to coordinators). Also made sure they route to the correct page
- FIxed pttrack.*.None in the workup view

**Comment by nakul2234** [comment]
1) The idea is to inactivate them manually so that the Coordinators will check each one at the ened of the day and make sure everything is done. If an attending signs and inactivates the patient, the coordinators have to search for all the names again when checking to make sure everything was done.
2) Most were UI improvements, so not much to test except the physical rendering. I edited previous tests to make them align with the new variables.

**Comment by justinrporter** [comment]
1) Awesome. This is a really good idea. Long-term we should think about coordinators signing off on a patient's chart as well?
2) cool cool. that makes sense.

Well done. I'm excited about this update.

**Pull request merged**
