### PR TITLE
did some work

### PR DESCRIPTION
**Pull request by zhouminerva**
I did some small things like change verbose names and make new links which are p inconsequential but bigger things
- added "outcome" field  to patients at the request of somebody
- added "attending" and "other volunteer" field to workups at the request of somebody
- yes i made tests

the report says I'm failing something... but I can't really tell what? on my computer I think the only ones I'm failing are the selenium ones bc mine isn't up to date. And circle isn't loading so I can't tell...

### CODE REVIEW

**Comment by zhouminerva** [comment]
1. Maybe I'm misunderstanding the concept of Foreign Key but of the outcomes (Referred, Lost to f/u, Following Up, etc): each Patient will only have one outcome (their current status) but each outcome will have been assigned to multiple patients? Like Referred will have all patients that have been referred right?
I figured not One to One because Patient A and Patient B could both be Outcome: Referred? And not one patient many outcomes because it's meant to be a status message not a tracking? 
Let me know if there's a better way though haha.

2. It opens the wiki page in a new tab instead of in the same window.

3. Xtine says because getting attendings to attest notes can be a problem so it's useful to track them down in those instances.
Personally, I don't think it's a problem if someone different attests? Should I make it an error though? Because attending is not a required field, I feel like putting more restrictions on it (when it's just more info for ease of life) could get annoying somehow later down the line.

4. Yeah, I just added a second field per Xtine's request. 
I actually thought about the M2M field but I was struggling to find a nice way to do that in the form... maybe I will try it though. Otherwise it'll eventually be like the 4 alternate phone numbers lol.

**Comment by justinrporter** [comment]
1. Oh shit you're right. I guess I had in my mind that outcome would be a "close out" note that you write, but obviously it's another of these categorical fields.
2. smart.
3. That's a good point. I like this idea: it's like a "request attestation" type of semantic.
4. Right. It's kind of a pain, though, you're right. I guess we could leave it for now. I think one-to-many is pretty easy to migrate to m2m...

**Comment by justinrporter** [comment]
👍

**Comment by justinrporter** [comment]
👍

**Pull request merged**
