### PR TITLE
PDF Export of Workups

### PR DESCRIPTION
**Pull request by nakul2234**

### CODE REVIEW

**Comment by justinrporter** [comment]
There is a lot of duplicated code between workup and pdf workup templates, it seems--perhaps we could use the template extension semantic to prevent duplicating this code?

**Comment by nakul2234** [comment]
@justinrporter Agreed! I fixed that in my last commit and am starting to write a few tests.

**Comment by justinrporter** [comment]
Nice, I love it!

Only one thing: I don't think using workup_pdf is a great name for a base template that's used in something that _doesn't_ produce pdfs...

**Comment by nakul2234** [comment]
`workup_body_text` might work better as a name for that template?

**Comment by justinrporter** [comment]
Totally. Or just `workup_body`, even...

**Pull request merged**
