### PR TITLE
Tab Views and Demographics App

### PR DESCRIPTION
**Pull request by nakul2234**
Also decided to tackle a few minor issues listed in the queue

### CODE REVIEW

**Comment by nakul2234** [comment]
@justinrporter Once you are fine with these edits and I push, can we try doing the Halstead update this afternoon/evening if you have some time? I think I keep making a few mistakes and wanted to watch you do it once and write some notes.

**Comment by justinrporter** [comment]
So, I'd prefer to have a separate demographics app, where the demographics model has a `OneToOne` relationship with patients. Do you think you could do that?

Additionally, we generally try to ship only one migration for a branch. That is, all of the database changes ought to be encapsulated in a single update, for clarity.

**Comment by nakul2234** [comment]
Yeah, I need to learn how to make a new app at some point. At this point, the app would be very light, but we could improve it later. I was thinking after you click submit for the patient basic info, a new form for demographics would come up. 

How would I do this? I know that once I create the new app that will create another set of of migrations. Squashing would make it all into one file which is something I don't want to do either.

**Comment by justinrporter** [comment]
Creating a new app is totally trivial. It's something like `./manage.py startapp [app name]` then you add it to the `INSTALLED_APPS` parameter in `settings.py`.

>  I was thinking after you click submit for the patient basic info, a new form for demographics would come up.

Remember the old "whoa! you don't have any demographics info." banner? I was thinking we bring that back. Or just redirect after patient creation (with a button to skip)?

> How would I do this?

You can just completely just delete the new migrations and run `makemigrations` again. You can use the `reset_db.sh` script to make sure the database is fresh. We can talk about this later?

**Comment by ecd25** [comment]
Can the button to skip it be really tiny or only for coordinators? I can
see why I would want to sometimes... But I mostly want it entered right
away when the volunteer or anyone adds the patient

**Comment by justinrporter** [comment]
In general, I am not a huge fan of hard failures when it's avoidable. I don't want the clinic to come to a grinding halt if somebody can't figure out how to interpret what the patient wrote on their intake form, or there's a bug in demographics validation, or something.

I think that automatic redirect on patient creation will be a sufficient nudge to fill out the demographics information. If it is not, we can revisit this decision in the future.

**Pull request merged**
